### ISSUE TITLE
Duplicate job in travis-ci config.

### ISSUE THREAD

**Issue by jbscoggi** [mutationpp/Mutationpp#97]
There is a duplicate job in the travis-ci config which can be removed.  In particular, this is written twice:

```yaml
- os: osx
      osx_image: xcode9.2
      <<: *osx_build
```

It is very easy to fix, just didn't want to forget about it.
